<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            // ─── ELECTRONICS ─────────────────────────────────────
            ['name' => 'Apple AirPods Pro 2nd Generation', 'description' => 'Active noise cancellation with adaptive transparency, personalized spatial audio, and MagSafe charging case with speaker and lanyard loop.', 'price' => 249.00, 'rating' => 4.8, 'reviews_count' => 45230, 'category' => 'Electronics', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['earbuds', 'wireless', 'apple', 'noise canceling', 'audio', 'airpods'])],
            ['name' => 'Samsung Galaxy S24 Ultra', 'description' => 'Titanium frame smartphone with 200MP camera, Galaxy AI features, S Pen built-in, and 5000mAh battery with 45W fast charging.', 'price' => 1299.99, 'rating' => 4.7, 'reviews_count' => 18760, 'category' => 'Electronics', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['phone', 'smartphone', 'samsung', 'galaxy', 'android', 'camera', '5g'])],
            ['name' => 'Apple iPhone 16 Pro Max', 'description' => '6.9-inch Super Retina XDR display, A18 Pro chip, 48MP camera system with 5x optical zoom, and all-day battery life.', 'price' => 1199.00, 'rating' => 4.8, 'reviews_count' => 32100, 'category' => 'Electronics', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['phone', 'smartphone', 'apple', 'iphone', 'ios', 'camera', '5g'])],
            ['name' => 'Google Pixel 9 Pro', 'description' => 'AI-powered smartphone with Tensor G4 chip, 50MP triple camera, 7 years of updates, and Magic Eraser photo editing.', 'price' => 999.00, 'rating' => 4.6, 'reviews_count' => 9870, 'category' => 'Electronics', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['phone', 'smartphone', 'google', 'pixel', 'android', 'camera', 'ai'])],
            ['name' => 'Sony A7 IV Mirrorless Camera', 'description' => 'Full-frame 33MP camera with real-time eye AF, 4K 60p video, 10fps burst shooting, and dual card slots.', 'price' => 2498.00, 'rating' => 4.7, 'reviews_count' => 6540, 'category' => 'Electronics', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['camera', 'mirrorless', 'photography', 'sony', 'full frame', 'video', '4k'])],
            ['name' => 'DJI Mini 4 Pro Drone', 'description' => 'Sub-249g drone with 4K/60fps HDR video, omnidirectional obstacle sensing, 34-min flight time, and ActiveTrack 360°.', 'price' => 759.00, 'rating' => 4.7, 'reviews_count' => 8230, 'category' => 'Electronics', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['drone', 'dji', 'camera', 'aerial', 'photography', 'video', '4k', 'flying'])],
            ['name' => 'GoPro HERO13 Black', 'description' => 'Waterproof action camera with 5.3K video, HyperSmooth 7.0 stabilization, GPS, and magnetic mounting system.', 'price' => 399.99, 'rating' => 4.5, 'reviews_count' => 14320, 'category' => 'Electronics', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['camera', 'action camera', 'gopro', 'waterproof', 'video', 'adventure', 'sports'])],
            ['name' => 'Sonos Era 300 Speaker', 'description' => 'Spatial audio speaker with Dolby Atmos, six drivers, Wi-Fi 6, Bluetooth, and Trueplay tuning technology.', 'price' => 449.00, 'rating' => 4.5, 'reviews_count' => 5670, 'category' => 'Electronics', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['speaker', 'sonos', 'spatial audio', 'dolby atmos', 'wifi', 'home audio', 'music'])],
            ['name' => 'Apple Watch Ultra 2', 'description' => '49mm titanium case, 3000 nit display, dual-frequency GPS, 36-hour battery, dive computer to 40m, and Action button.', 'price' => 799.00, 'rating' => 4.7, 'reviews_count' => 11200, 'category' => 'Wearables', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['smartwatch', 'apple', 'fitness', 'gps', 'diving', 'hiking', 'titanium', 'health'])],
            ['name' => 'Garmin Fenix 8 Solar', 'description' => 'Premium multisport GPS watch with solar charging, AMOLED display, topo maps, and up to 48 days battery life.', 'price' => 999.99, 'rating' => 4.8, 'reviews_count' => 4560, 'category' => 'Wearables', 'image_url' => null, 'is_prime' => false, 'tags' => json_encode(['smartwatch', 'garmin', 'fitness', 'gps', 'solar', 'hiking', 'running', 'outdoor'])],
            ['name' => 'Jabra Elite 85t Earbuds', 'description' => 'True wireless earbuds with advanced ANC, 6 microphones, customizable sound profiles, and Qi wireless charging.', 'price' => 179.99, 'rating' => 4.4, 'reviews_count' => 19870, 'category' => 'Electronics', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['earbuds', 'wireless', 'jabra', 'noise canceling', 'audio', 'bluetooth'])],
            ['name' => 'Sennheiser Momentum 4 Wireless', 'description' => 'Audiophile-grade wireless headphones with 60-hour battery, adaptive noise cancellation, and premium leather headband.', 'price' => 349.95, 'rating' => 4.6, 'reviews_count' => 7650, 'category' => 'Electronics', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['headphones', 'wireless', 'sennheiser', 'audiophile', 'noise canceling', 'premium', 'audio'])],
            ['name' => 'Marshall Stanmore III Bluetooth Speaker', 'description' => 'Iconic design home speaker with dynamic loudness, adjustable bass/treble, HDMI connectivity, and multi-room support.', 'price' => 379.99, 'rating' => 4.6, 'reviews_count' => 6780, 'category' => 'Electronics', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['speaker', 'marshall', 'bluetooth', 'home audio', 'music', 'vintage', 'rock'])],
            ['name' => 'Fujifilm X-T5 Mirrorless Camera', 'description' => '40MP APS-C sensor with in-body stabilization, 6.2K video, classic film simulations, and retro dial-based controls.', 'price' => 1699.00, 'rating' => 4.8, 'reviews_count' => 5430, 'category' => 'Electronics', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['camera', 'mirrorless', 'fujifilm', 'photography', 'retro', 'film simulation', 'video'])],
            ['name' => 'Roku Ultra 4K Streaming Player', 'description' => 'Premium streaming device with Dolby Vision, Atmos support, ethernet port, USB, and voice remote with headphone jack.', 'price' => 99.99, 'rating' => 4.5, 'reviews_count' => 23450, 'category' => 'Electronics', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['streaming', 'roku', '4k', 'dolby', 'tv', 'entertainment', 'media player'])],
            ['name' => 'Apple TV 4K 128GB', 'description' => 'A15 Bionic chip streaming box with Dolby Vision, Atmos, Siri remote, Thread support, and Apple Arcade gaming.', 'price' => 149.00, 'rating' => 4.7, 'reviews_count' => 15670, 'category' => 'Electronics', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['streaming', 'apple', '4k', 'dolby', 'tv', 'entertainment', 'gaming', 'smart home'])],
            ['name' => 'Anker Soundcore Space A40 Earbuds', 'description' => 'Compact wireless earbuds with adaptive ANC, 50-hour total playtime, LDAC hi-res audio, and wireless charging case.', 'price' => 79.99, 'rating' => 4.4, 'reviews_count' => 28900, 'category' => 'Electronics', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['earbuds', 'wireless', 'anker', 'noise canceling', 'budget', 'audio', 'bluetooth'])],
            ['name' => 'Canon EOS R6 Mark II', 'description' => 'Full-frame mirrorless with 24.2MP sensor, 40fps continuous shooting, 4K 60p video, and advanced subject detection AF.', 'price' => 2499.00, 'rating' => 4.7, 'reviews_count' => 4890, 'category' => 'Electronics', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['camera', 'mirrorless', 'canon', 'photography', 'full frame', 'video', 'professional'])],
            ['name' => 'Nvidia Shield TV Pro', 'description' => '4K HDR streaming media player with Tegra X1+ processor, Dolby Vision, AI upscaling, and GeForce NOW cloud gaming.', 'price' => 199.99, 'rating' => 4.6, 'reviews_count' => 11230, 'category' => 'Electronics', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['streaming', 'nvidia', '4k', 'gaming', 'android tv', 'media player', 'cloud gaming'])],
            ['name' => 'Bang & Olufsen Beoplay H95', 'description' => 'Luxury wireless headphones with titanium drivers, adaptive ANC, 38-hour battery, and lambskin ear cushions.', 'price' => 899.00, 'rating' => 4.5, 'reviews_count' => 2340, 'category' => 'Electronics', 'image_url' => null, 'is_prime' => false, 'tags' => json_encode(['headphones', 'luxury', 'bang olufsen', 'wireless', 'noise canceling', 'premium', 'audiophile'])],

            // ─── COMPUTERS & ACCESSORIES ─────────────────────────
            ['name' => 'Apple Mac Mini M4 Pro', 'description' => 'Compact desktop with M4 Pro chip, 18GB unified memory, Thunderbolt 5, and up to 22-core GPU for creative professionals.', 'price' => 1599.00, 'rating' => 4.8, 'reviews_count' => 6780, 'category' => 'Computers', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['desktop', 'apple', 'mac mini', 'computer', 'compact', 'professional', 'creative'])],
            ['name' => 'Dell XPS 16 Laptop', 'description' => '16-inch OLED touchscreen, Intel Core Ultra 9, 32GB RAM, 1TB SSD, and edge-to-edge InfinityEdge display.', 'price' => 1899.00, 'rating' => 4.5, 'reviews_count' => 5430, 'category' => 'Computers', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['laptop', 'dell', 'xps', 'oled', 'computer', 'thin', 'professional', 'windows'])],
            ['name' => 'Lenovo ThinkPad X1 Carbon Gen 12', 'description' => 'Business ultrabook with Intel Core Ultra 7, 14-inch 2.8K OLED, 57Wh battery, fingerprint reader, and MIL-STD tested.', 'price' => 1649.00, 'rating' => 4.6, 'reviews_count' => 7890, 'category' => 'Computers', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['laptop', 'lenovo', 'thinkpad', 'business', 'ultrabook', 'windows', 'durable'])],
            ['name' => 'ASUS ROG Strix G16 Gaming Laptop', 'description' => 'Gaming powerhouse with RTX 4070, Intel i9-14900HX, 16-inch 240Hz display, and per-key RGB keyboard.', 'price' => 1799.99, 'rating' => 4.6, 'reviews_count' => 4560, 'category' => 'Computers', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['laptop', 'gaming', 'asus', 'rog', 'nvidia', 'rtx', 'high performance', 'rgb'])],
            ['name' => 'Raspberry Pi 5 8GB', 'description' => '2.4GHz quad-core Arm Cortex-A76, 8GB LPDDR4X RAM, dual 4K HDMI output, PCIe 2.0, and USB 3.0.', 'price' => 80.00, 'rating' => 4.7, 'reviews_count' => 12340, 'category' => 'Computers', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['raspberry pi', 'single board', 'computer', 'maker', 'diy', 'programming', 'linux', 'education'])],
            ['name' => 'Logitech MX Keys S Keyboard', 'description' => 'Low-profile wireless keyboard with smart backlighting, Easy-Switch for 3 devices, and programmable keys.', 'price' => 109.99, 'rating' => 4.6, 'reviews_count' => 14560, 'category' => 'Computers', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['keyboard', 'wireless', 'logitech', 'ergonomic', 'work', 'productivity', 'typing'])],
            ['name' => 'Samsung 990 Pro 2TB NVMe SSD', 'description' => 'PCIe 4.0 NVMe M.2 SSD with 7,450 MB/s read speed, hardware encryption, and Samsung Magician software.', 'price' => 159.99, 'rating' => 4.8, 'reviews_count' => 18900, 'category' => 'Computers', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['ssd', 'storage', 'samsung', 'nvme', 'fast', 'computer', 'upgrade', 'pcie'])],
            ['name' => 'CalDigit TS4 Thunderbolt 4 Dock', 'description' => '18-port docking station with 98W charging, 2.5GbE, SD card reader, and 3x Thunderbolt 4 downstream ports.', 'price' => 399.99, 'rating' => 4.7, 'reviews_count' => 5670, 'category' => 'Computers', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['dock', 'thunderbolt', 'usb', 'hub', 'workstation', 'macbook', 'laptop', 'productivity'])],
            ['name' => 'Keychron Q1 Pro Mechanical Keyboard', 'description' => 'Wireless 75% layout with Gateron Jupiter Brown switches, QMK/VIA firmware, aluminum body, and hot-swappable sockets.', 'price' => 199.00, 'rating' => 4.7, 'reviews_count' => 8900, 'category' => 'Computers', 'image_url' => null, 'is_prime' => false, 'tags' => json_encode(['keyboard', 'mechanical', 'keychron', 'wireless', 'typing', 'custom', 'qmk', 'programming'])],
            ['name' => 'LG 27" UltraGear OLED Gaming Monitor', 'description' => '27-inch WQHD OLED, 240Hz refresh rate, 0.03ms response time, G-Sync compatible, and anti-glare coating.', 'price' => 899.99, 'rating' => 4.7, 'reviews_count' => 6780, 'category' => 'Computers', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['monitor', 'gaming', 'oled', 'lg', '240hz', 'display', 'screen', 'ultrawide'])],
            ['name' => 'Apple Studio Display', 'description' => '27-inch 5K Retina display with 600 nits brightness, 12MP ultrawide camera, six-speaker sound system, and three USB-C ports.', 'price' => 1599.00, 'rating' => 4.4, 'reviews_count' => 4320, 'category' => 'Computers', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['monitor', 'apple', '5k', 'display', 'screen', 'professional', 'creative', 'retina'])],
            ['name' => 'Elgato Stream Deck MK.2', 'description' => '15 customizable LCD keys for streaming, productivity macros, smart home control, and app switching with drag-and-drop setup.', 'price' => 149.99, 'rating' => 4.7, 'reviews_count' => 21340, 'category' => 'Computers', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['streaming', 'elgato', 'macro', 'productivity', 'content creation', 'twitch', 'youtube'])],
            ['name' => 'Corsair Vengeance DDR5 32GB RAM Kit', 'description' => 'High-performance DDR5-6000MHz dual-channel memory kit with Intel XMP 3.0 support and compact heatspreader.', 'price' => 94.99, 'rating' => 4.7, 'reviews_count' => 15670, 'category' => 'Computers', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['ram', 'memory', 'ddr5', 'corsair', 'computer', 'upgrade', 'gaming', 'performance'])],

            // ─── GAMING ──────────────────────────────────────────
            ['name' => 'Nintendo Switch OLED Model', 'description' => '7-inch OLED screen, 64GB storage, enhanced audio, wide adjustable stand, and wired LAN port in dock.', 'price' => 349.99, 'rating' => 4.8, 'reviews_count' => 42100, 'category' => 'Gaming', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['gaming', 'nintendo', 'switch', 'console', 'portable', 'handheld', 'oled'])],
            ['name' => 'Xbox Series X 1TB', 'description' => '12 teraflops of processing power, 4K gaming at 120fps, Quick Resume, and backward compatibility with thousands of games.', 'price' => 499.99, 'rating' => 4.7, 'reviews_count' => 25670, 'category' => 'Gaming', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['gaming', 'xbox', 'microsoft', 'console', '4k', 'game pass', 'entertainment'])],
            ['name' => 'Steam Deck OLED 1TB', 'description' => 'Portable PC gaming with 7.4-inch HDR OLED, AMD APU, Wi-Fi 6E, 6-hour battery, and full Steam library access.', 'price' => 649.00, 'rating' => 4.8, 'reviews_count' => 11230, 'category' => 'Gaming', 'image_url' => null, 'is_prime' => false, 'tags' => json_encode(['gaming', 'steam deck', 'valve', 'portable', 'pc gaming', 'handheld', 'oled', 'steam'])],
            ['name' => 'SteelSeries Arctis Nova Pro Wireless', 'description' => 'Premium gaming headset with dual wireless, active ANC, hot-swap battery system, and hi-fi 360° spatial audio.', 'price' => 349.99, 'rating' => 4.5, 'reviews_count' => 8760, 'category' => 'Gaming', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['gaming headset', 'wireless', 'steelseries', 'noise canceling', 'audio', 'pc', 'playstation'])],
            ['name' => 'Razer Viper V3 Pro Gaming Mouse', 'description' => 'Ultra-lightweight 54g wireless gaming mouse with 35K DPI sensor, 90-hour battery, and optical switches.', 'price' => 159.99, 'rating' => 4.6, 'reviews_count' => 6540, 'category' => 'Gaming', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['mouse', 'gaming', 'razer', 'wireless', 'lightweight', 'esports', 'fps'])],
            ['name' => 'Secretlab Titan Evo Gaming Chair', 'description' => 'Ergonomic gaming chair with 4-way L-ADAPT lumbar, magnetic memory foam headrest, Neo Hybrid Leatherette, and cold-cure foam.', 'price' => 519.00, 'rating' => 4.7, 'reviews_count' => 14560, 'category' => 'Gaming', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['chair', 'gaming', 'ergonomic', 'office', 'secretlab', 'lumbar support', 'comfortable'])],
            ['name' => 'Elgato HD60 X Capture Card', 'description' => '4K30 HDR10 passthrough, 1080p60 capture, VRR support, and zero-lag preview for streaming and recording.', 'price' => 159.99, 'rating' => 4.5, 'reviews_count' => 7890, 'category' => 'Gaming', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['capture card', 'streaming', 'elgato', 'content creation', 'recording', 'twitch', 'youtube'])],
            ['name' => 'Meta Quest 3 128GB', 'description' => 'Mixed reality headset with Snapdragon XR2 Gen 2, full-color passthrough, pancake optics, and 120Hz refresh rate.', 'price' => 499.99, 'rating' => 4.5, 'reviews_count' => 16780, 'category' => 'Gaming', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['vr', 'virtual reality', 'meta', 'quest', 'mixed reality', 'headset', 'gaming', 'immersive'])],
            ['name' => 'Backbone One Mobile Game Controller', 'description' => 'Snap-on controller for iPhone and Android with low-latency connection, passthrough charging, and dedicated app.', 'price' => 99.99, 'rating' => 4.6, 'reviews_count' => 19870, 'category' => 'Gaming', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['controller', 'mobile gaming', 'iphone', 'android', 'backbone', 'portable', 'cloud gaming'])],
            ['name' => 'HyperX Cloud III Wireless Gaming Headset', 'description' => '53mm drivers, DTS Headphone:X spatial audio, 120-hour battery, memory foam cushions, and detachable mic.', 'price' => 119.99, 'rating' => 4.5, 'reviews_count' => 11230, 'category' => 'Gaming', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['gaming headset', 'wireless', 'hyperx', 'audio', 'comfortable', 'long battery', 'pc'])],

            // ─── HOME & SMART HOME ───────────────────────────────
            ['name' => 'Amazon Echo Show 10', 'description' => '10.1-inch HD screen that rotates to follow you, Zigbee smart home hub, 13MP camera, and premium speakers.', 'price' => 249.99, 'rating' => 4.4, 'reviews_count' => 18760, 'category' => 'Smart Home', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['smart home', 'alexa', 'amazon', 'smart display', 'voice assistant', 'hub', 'speaker'])],
            ['name' => 'Google Nest Learning Thermostat 4th Gen', 'description' => 'AI-powered thermostat with edge-to-edge display, auto-scheduling, energy savings dashboard, and Matter support.', 'price' => 279.99, 'rating' => 4.5, 'reviews_count' => 12340, 'category' => 'Smart Home', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['thermostat', 'smart home', 'google', 'nest', 'energy saving', 'heating', 'cooling', 'ai'])],
            ['name' => 'Philips Hue Starter Kit (4 Bulbs + Bridge)', 'description' => 'Smart LED bulbs with 16 million colors, voice control, app scheduling, and Hue Bridge for up to 50 lights.', 'price' => 179.99, 'rating' => 4.6, 'reviews_count' => 34560, 'category' => 'Smart Home', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['smart lights', 'philips hue', 'smart home', 'led', 'color', 'automation', 'mood lighting'])],
            ['name' => 'Ring Video Doorbell Pro 2', 'description' => 'Head-to-toe HD+ video doorbell with 3D motion detection, Bird\'s Eye View, quick replies, and hardwired installation.', 'price' => 229.99, 'rating' => 4.4, 'reviews_count' => 23450, 'category' => 'Smart Home', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['doorbell', 'security', 'ring', 'smart home', 'camera', 'video', 'safety'])],
            ['name' => 'Ecobee Smart Thermostat Premium', 'description' => 'Built-in air quality monitor, Siri and Alexa, SmartSensor included, zinc metal body, and energy rebate eligible.', 'price' => 249.99, 'rating' => 4.5, 'reviews_count' => 8760, 'category' => 'Smart Home', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['thermostat', 'smart home', 'ecobee', 'energy saving', 'air quality', 'alexa', 'siri'])],
            ['name' => 'Arlo Pro 5S Security Camera 2-Pack', 'description' => '2K HDR wireless security cameras with color night vision, 160° field of view, built-in spotlight, and 6-month battery.', 'price' => 329.99, 'rating' => 4.3, 'reviews_count' => 15670, 'category' => 'Smart Home', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['security camera', 'arlo', 'smart home', 'wireless', 'outdoor', 'night vision', 'safety'])],
            ['name' => 'Shark AI Ultra Robot Vacuum & Mop', 'description' => 'Self-emptying base, precision home mapping, 30-day capacity, sonic mopping, and AI obstacle avoidance.', 'price' => 599.99, 'rating' => 4.4, 'reviews_count' => 9870, 'category' => 'Home', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['robot vacuum', 'mop', 'shark', 'smart home', 'cleaning', 'automatic', 'self emptying'])],
            ['name' => 'Levoit Core 400S Air Purifier', 'description' => 'Large room HEPA air purifier with smart Wi-Fi, auto mode, laser dust sensor, and 403 sq ft coverage.', 'price' => 219.99, 'rating' => 4.6, 'reviews_count' => 27890, 'category' => 'Home', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['air purifier', 'hepa', 'levoit', 'smart home', 'allergy', 'clean air', 'dust', 'health'])],
            ['name' => 'Dyson Purifier Hot+Cool Formaldehyde', 'description' => 'Air purifier, heater, and fan with HEPA H13 filter, formaldehyde detection, and Dyson Link app control.', 'price' => 749.99, 'rating' => 4.4, 'reviews_count' => 6540, 'category' => 'Home', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['air purifier', 'heater', 'fan', 'dyson', 'smart home', 'allergy', 'formaldehyde', 'clean air'])],
            ['name' => 'August Wi-Fi Smart Lock 4th Gen', 'description' => 'Retrofit smart lock with auto-unlock, DoorSense, voice assistant support, and no hub required.', 'price' => 229.99, 'rating' => 4.3, 'reviews_count' => 14560, 'category' => 'Smart Home', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['smart lock', 'august', 'smart home', 'security', 'keyless', 'wifi', 'door'])],
            ['name' => 'iRobot Braava Jet m6 Robot Mop', 'description' => 'Precision jet spray and vibrating cleaning head, smart mapping, Imprint Link for automatic mopping after vacuuming.', 'price' => 449.99, 'rating' => 4.2, 'reviews_count' => 8760, 'category' => 'Home', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['robot mop', 'irobot', 'braava', 'cleaning', 'smart home', 'mopping', 'automatic', 'floor'])],
            ['name' => 'Nanoleaf Shapes Hexagons Smarter Kit', 'description' => 'Modular RGB light panels with touch-reactive controls, music sync, Thread border router, and screen mirror.', 'price' => 199.99, 'rating' => 4.5, 'reviews_count' => 11230, 'category' => 'Smart Home', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['smart lights', 'nanoleaf', 'rgb', 'wall panels', 'decor', 'gaming room', 'mood lighting', 'music sync'])],

            // ─── KITCHEN & COOKING ───────────────────────────────
            ['name' => 'KitchenAid Artisan Stand Mixer 5-Quart', 'description' => 'Iconic tilt-head stand mixer with 10 speeds, planetary mixing action, and 15+ optional attachments.', 'price' => 449.99, 'rating' => 4.8, 'reviews_count' => 67890, 'category' => 'Kitchen', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['mixer', 'kitchenaid', 'baking', 'kitchen', 'cooking', 'stand mixer', 'appliance'])],
            ['name' => 'Vitamix A3500 Ascent Series Blender', 'description' => 'Smart blender with touchscreen controls, 5 program settings, self-detect containers, and variable speed dial.', 'price' => 649.95, 'rating' => 4.7, 'reviews_count' => 12340, 'category' => 'Kitchen', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['blender', 'vitamix', 'smoothie', 'kitchen', 'cooking', 'juicing', 'smart'])],
            ['name' => 'Ninja Creami Ice Cream Maker', 'description' => 'Turn frozen bases into ice cream, sorbet, gelato, milkshakes, smoothie bowls, and lite ice cream in minutes.', 'price' => 199.99, 'rating' => 4.5, 'reviews_count' => 34560, 'category' => 'Kitchen', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['ice cream', 'ninja', 'dessert', 'kitchen', 'frozen', 'smoothie', 'gelato'])],
            ['name' => 'Le Creuset Signature Dutch Oven 5.5 Qt', 'description' => 'Enameled cast iron with superior heat distribution, tight-fitting lid, colorful exterior, and lifetime warranty.', 'price' => 419.95, 'rating' => 4.8, 'reviews_count' => 23450, 'category' => 'Kitchen', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['dutch oven', 'le creuset', 'cast iron', 'cooking', 'kitchen', 'premium', 'baking', 'stew'])],
            ['name' => 'Ooni Koda 16 Gas Pizza Oven', 'description' => 'Outdoor gas-powered pizza oven reaching 950°F, cooks 16-inch pizzas in 60 seconds with L-shaped flame.', 'price' => 599.00, 'rating' => 4.7, 'reviews_count' => 8760, 'category' => 'Kitchen', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['pizza oven', 'ooni', 'outdoor cooking', 'pizza', 'gas', 'grilling', 'party'])],
            ['name' => 'Nespresso Vertuo Next Coffee Machine', 'description' => 'Centrifusion technology brews 5 cup sizes, barcode-reading capsule system, and connected app with 30+ blends.', 'price' => 179.00, 'rating' => 4.4, 'reviews_count' => 19870, 'category' => 'Kitchen', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['coffee', 'nespresso', 'espresso', 'capsule', 'kitchen', 'quick', 'morning', 'machine'])],
            ['name' => 'Traeger Ironwood 650 Pellet Grill', 'description' => 'WiFIRE enabled wood pellet grill with Super Smoke mode, 650 sq in cooking space, and downdraft exhaust system.', 'price' => 1299.99, 'rating' => 4.6, 'reviews_count' => 5670, 'category' => 'Kitchen', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['grill', 'bbq', 'traeger', 'pellet', 'smoking', 'outdoor cooking', 'wifi', 'meat'])],
            ['name' => 'Zwilling Pro 7-Piece Knife Block Set', 'description' => 'German-forged stainless steel knives with ergonomic bolster, ice-hardened blade, and natural wood block.', 'price' => 399.99, 'rating' => 4.7, 'reviews_count' => 11230, 'category' => 'Kitchen', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['knives', 'zwilling', 'kitchen', 'chef', 'cooking', 'cutting', 'german', 'professional'])],
            ['name' => 'Staub Cast Iron Cocotte 4 Qt', 'description' => 'French enameled cast iron with self-basting lid spikes, black matte enamel interior, and induction compatible.', 'price' => 329.99, 'rating' => 4.8, 'reviews_count' => 7890, 'category' => 'Kitchen', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['cast iron', 'staub', 'dutch oven', 'cooking', 'kitchen', 'french', 'premium', 'braising'])],
            ['name' => 'Sage (Breville) Smart Oven Air Fryer Pro', 'description' => '13 cooking functions including air fry, dehydrate, slow cook, and proof with Element IQ heat management.', 'price' => 399.95, 'rating' => 4.6, 'reviews_count' => 14560, 'category' => 'Kitchen', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['oven', 'air fryer', 'breville', 'countertop', 'kitchen', 'toaster', 'dehydrator', 'cooking'])],
            ['name' => 'Fellow Stagg EKG Electric Kettle', 'description' => 'Pour-over kettle with variable temperature control, built-in brew timer, LCD screen, and matte black finish.', 'price' => 195.00, 'rating' => 4.7, 'reviews_count' => 9870, 'category' => 'Kitchen', 'image_url' => null, 'is_prime' => false, 'tags' => json_encode(['kettle', 'coffee', 'pour over', 'fellow', 'tea', 'temperature', 'kitchen', 'gooseneck'])],
            ['name' => 'Cuisinart 14-Cup Food Processor', 'description' => '720-watt motor with BladeLock system, large feed tube, stainless steel blades, and dishwasher-safe parts.', 'price' => 249.99, 'rating' => 4.6, 'reviews_count' => 18760, 'category' => 'Kitchen', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['food processor', 'cuisinart', 'kitchen', 'cooking', 'chopping', 'blending', 'meal prep'])],

            // ─── FITNESS & HEALTH ────────────────────────────────
            ['name' => 'Peloton Bike+', 'description' => '24-inch rotating HD touchscreen, auto-follow resistance, Apple GymKit, 4-channel audio, and thousands of live classes.', 'price' => 2495.00, 'rating' => 4.6, 'reviews_count' => 8760, 'category' => 'Fitness', 'image_url' => null, 'is_prime' => false, 'tags' => json_encode(['exercise bike', 'peloton', 'cycling', 'cardio', 'fitness', 'home gym', 'spin', 'classes'])],
            ['name' => 'Bowflex SelectTech 552 Dumbbells', 'description' => 'Adjustable dumbbells replacing 15 sets of weights, 5 to 52.5 lbs each, with quick dial adjustment.', 'price' => 429.00, 'rating' => 4.7, 'reviews_count' => 34560, 'category' => 'Fitness', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['dumbbells', 'adjustable', 'bowflex', 'weights', 'strength', 'home gym', 'fitness', 'workout'])],
            ['name' => 'NordicTrack Commercial 1750 Treadmill', 'description' => '14-inch tilt-and-pivot touchscreen, -3% to 15% incline, 12 MPH speed, iFIT membership, and FlexSelect cushioning.', 'price' => 1799.00, 'rating' => 4.4, 'reviews_count' => 11230, 'category' => 'Fitness', 'image_url' => null, 'is_prime' => false, 'tags' => json_encode(['treadmill', 'nordictrack', 'running', 'cardio', 'home gym', 'fitness', 'ifit', 'walking'])],
            ['name' => 'Fitbit Charge 6', 'description' => 'Advanced fitness tracker with built-in GPS, heart rate zones, stress management score, and 7-day battery.', 'price' => 159.95, 'rating' => 4.3, 'reviews_count' => 23450, 'category' => 'Wearables', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['fitness tracker', 'fitbit', 'health', 'gps', 'heart rate', 'sleep', 'steps', 'wearable'])],
            ['name' => 'Hyperice Hypervolt 2 Pro', 'description' => 'Quiet percussion massage device with 5 speeds, 5 interchangeable heads, and Bluetooth app connectivity.', 'price' => 329.00, 'rating' => 4.5, 'reviews_count' => 8760, 'category' => 'Health', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['massage gun', 'hyperice', 'recovery', 'muscle', 'therapy', 'fitness', 'percussion'])],
            ['name' => 'Manduka PRO Yoga Mat 6mm', 'description' => 'Professional-grade yoga mat with closed-cell surface, lifetime guarantee, dense cushioning, and non-toxic materials.', 'price' => 132.00, 'rating' => 4.7, 'reviews_count' => 15670, 'category' => 'Fitness', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['yoga mat', 'manduka', 'yoga', 'fitness', 'exercise', 'stretching', 'pilates', 'meditation'])],
            ['name' => 'Whoop 4.0 Fitness Tracker', 'description' => 'Screen-free wearable tracking strain, recovery, and sleep with 5-day battery and personalized insights.', 'price' => 0.00, 'rating' => 4.2, 'reviews_count' => 6540, 'category' => 'Wearables', 'image_url' => null, 'is_prime' => false, 'tags' => json_encode(['fitness tracker', 'whoop', 'recovery', 'sleep', 'strain', 'health', 'wearable', 'subscription'])],
            ['name' => 'TRX PRO4 Suspension Trainer System', 'description' => 'Commercial-grade suspension trainer with steel carabiner, locking loop, adjustable foot cradles, and door anchor.', 'price' => 249.95, 'rating' => 4.7, 'reviews_count' => 12340, 'category' => 'Fitness', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['suspension trainer', 'trx', 'bodyweight', 'strength', 'home gym', 'portable', 'fitness'])],
            ['name' => 'Withings Body+ Smart Scale', 'description' => 'Wi-Fi connected scale measuring weight, BMI, body fat, water percentage, and muscle/bone mass with app tracking.', 'price' => 99.95, 'rating' => 4.4, 'reviews_count' => 19870, 'category' => 'Health', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['scale', 'smart', 'withings', 'weight', 'body fat', 'health', 'fitness', 'tracking'])],
            ['name' => 'Therabody RecoveryAir JetBoots', 'description' => 'Pneumatic compression boots with 4 pressure levels, FastFlush technology, and TruGrade calibration per zone.', 'price' => 899.00, 'rating' => 4.4, 'reviews_count' => 3450, 'category' => 'Health', 'image_url' => null, 'is_prime' => false, 'tags' => json_encode(['compression boots', 'recovery', 'therabody', 'legs', 'circulation', 'athlete', 'muscle'])],

            // ─── OUTDOOR & ADVENTURE ─────────────────────────────
            ['name' => 'Osprey Atmos AG 65 Backpack', 'description' => 'Anti-gravity suspension system, fit-on-the-fly hipbelt, Stow-on-the-Go trekking pole attachment, and rain cover.', 'price' => 300.00, 'rating' => 4.8, 'reviews_count' => 9870, 'category' => 'Outdoors', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['backpack', 'osprey', 'hiking', 'camping', 'outdoor', 'trekking', 'travel', 'lightweight'])],
            ['name' => 'REI Co-op Flash 22 Daypack', 'description' => 'Ultralight 22L daypack with hipbelt pockets, trekking pole loops, hydration-compatible, and only 13 oz.', 'price' => 54.95, 'rating' => 4.6, 'reviews_count' => 14560, 'category' => 'Outdoors', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['daypack', 'rei', 'hiking', 'lightweight', 'backpack', 'outdoor', 'trail'])],
            ['name' => 'YETI Tundra 45 Hard Cooler', 'description' => 'Rotomolded construction, PermaFrost insulation, bear-resistant certified, and T-Rex lid latches.', 'price' => 325.00, 'rating' => 4.7, 'reviews_count' => 18760, 'category' => 'Outdoors', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['cooler', 'yeti', 'camping', 'outdoor', 'ice', 'cold', 'durable', 'beach'])],
            ['name' => 'Black Diamond Spot 400-R Headlamp', 'description' => 'Rechargeable 400-lumen headlamp with night vision mode, waterproof IP67, and memory brightness setting.', 'price' => 49.95, 'rating' => 4.6, 'reviews_count' => 23450, 'category' => 'Outdoors', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['headlamp', 'black diamond', 'camping', 'hiking', 'light', 'rechargeable', 'night', 'outdoor'])],
            ['name' => 'Stanley Classic Legendary Bottle 2 Qt', 'description' => 'Double-wall vacuum insulated stainless steel thermos, keeps drinks hot 45 hours or cold 48 hours.', 'price' => 50.00, 'rating' => 4.7, 'reviews_count' => 45670, 'category' => 'Outdoors', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['thermos', 'stanley', 'insulated', 'hot drinks', 'cold drinks', 'camping', 'durable', 'outdoor'])],
            ['name' => 'Patagonia Black Hole Duffel 55L', 'description' => 'Ultralight, weather-resistant duffel with padded shoulder straps, daisy chains, and 100% recycled body fabric.', 'price' => 169.00, 'rating' => 4.7, 'reviews_count' => 8760, 'category' => 'Outdoors', 'image_url' => null, 'is_prime' => false, 'tags' => json_encode(['duffel', 'patagonia', 'travel', 'bag', 'outdoor', 'waterproof', 'recycled', 'adventure'])],
            ['name' => 'Salomon X Ultra 4 GTX Hiking Shoes', 'description' => 'Gore-Tex waterproof hiking shoes with Contagrip MA outsole, Advanced Chassis, and SensiFit cradle.', 'price' => 165.00, 'rating' => 4.6, 'reviews_count' => 11230, 'category' => 'Outdoors', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['hiking shoes', 'salomon', 'waterproof', 'gore-tex', 'trail', 'outdoor', 'trekking'])],
            ['name' => 'MSR Hubba Hubba NX 2-Person Tent', 'description' => 'Ultralight backpacking tent at 3 lbs, freestanding, 2 doors, 2 vestibules, and stargazing fly mode.', 'price' => 449.95, 'rating' => 4.7, 'reviews_count' => 6540, 'category' => 'Outdoors', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['tent', 'msr', 'camping', 'backpacking', 'ultralight', '2-person', 'outdoor', 'shelter'])],
            ['name' => 'Garmin inReach Mini 2 Satellite Communicator', 'description' => 'Compact satellite messenger with SOS, two-way texting, GPS tracking, weather forecasts, and 14-day battery.', 'price' => 399.99, 'rating' => 4.6, 'reviews_count' => 7890, 'category' => 'Outdoors', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['satellite communicator', 'garmin', 'gps', 'safety', 'sos', 'hiking', 'remote', 'emergency'])],
            ['name' => 'BioLite CampStove 2+', 'description' => 'Wood-burning camp stove that generates electricity to charge devices via USB, with 3W power output and LED dashboard.', 'price' => 149.95, 'rating' => 4.3, 'reviews_count' => 5670, 'category' => 'Outdoors', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['camp stove', 'biolite', 'camping', 'cooking', 'charging', 'usb', 'fire', 'outdoor', 'off grid'])],

            // ─── CLOTHING & FASHION ──────────────────────────────
            ['name' => 'Arc\'teryx Beta LT Jacket', 'description' => 'Lightweight Gore-Tex waterproof shell with helmet-compatible StormHood, pit zips, and articulated patterning.', 'price' => 450.00, 'rating' => 4.7, 'reviews_count' => 6540, 'category' => 'Clothing', 'image_url' => null, 'is_prime' => false, 'tags' => json_encode(['jacket', 'arcteryx', 'waterproof', 'gore-tex', 'outdoor', 'rain', 'shell', 'hiking'])],
            ['name' => 'The North Face ThermoBall Eco Jacket', 'description' => 'Synthetic insulation that continues to insulate when wet, packable design, and made with recycled materials.', 'price' => 220.00, 'rating' => 4.6, 'reviews_count' => 14560, 'category' => 'Clothing', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['jacket', 'north face', 'insulated', 'warm', 'winter', 'packable', 'outdoor', 'recycled'])],
            ['name' => 'Allbirds Tree Runners', 'description' => 'Lightweight everyday sneakers made from eucalyptus tree fiber, carbon-negative sole, and machine washable.', 'price' => 98.00, 'rating' => 4.4, 'reviews_count' => 23450, 'category' => 'Shoes', 'image_url' => null, 'is_prime' => false, 'tags' => json_encode(['shoes', 'sneakers', 'allbirds', 'sustainable', 'comfortable', 'lightweight', 'casual', 'eco'])],
            ['name' => 'Lululemon Align High-Rise Pants 25"', 'description' => 'Buttery soft Nulu fabric leggings with four-way stretch, no front seams, and hidden waistband pocket.', 'price' => 98.00, 'rating' => 4.7, 'reviews_count' => 45670, 'category' => 'Clothing', 'image_url' => null, 'is_prime' => false, 'tags' => json_encode(['leggings', 'lululemon', 'yoga', 'fitness', 'comfortable', 'stretchy', 'athleisure', 'women'])],
            ['name' => 'Merrell Moab 3 Mid Waterproof Boot', 'description' => 'Classic hiking boot with Vibram TC5+ outsole, bellows tongue, protective toe cap, and recycled laces.', 'price' => 149.99, 'rating' => 4.5, 'reviews_count' => 34560, 'category' => 'Shoes', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['hiking boots', 'merrell', 'waterproof', 'outdoor', 'trail', 'mid-cut', 'durable', 'trekking'])],
            ['name' => 'Adidas Ultraboost Light Running Shoes', 'description' => 'Lightest Ultraboost ever with Light BOOST midsole, Continental rubber outsole, and Primeknit+ upper.', 'price' => 190.00, 'rating' => 4.5, 'reviews_count' => 18760, 'category' => 'Shoes', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['running shoes', 'adidas', 'ultraboost', 'lightweight', 'cushioned', 'sports', 'athletic'])],
            ['name' => 'Hoka Clifton 9 Running Shoes', 'description' => 'Lightweight cushioned running shoe with compression-molded EVA midsole, breathable mesh, and meta-rocker geometry.', 'price' => 145.00, 'rating' => 4.6, 'reviews_count' => 21340, 'category' => 'Shoes', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['running shoes', 'hoka', 'cushioned', 'lightweight', 'comfortable', 'sports', 'marathon'])],
            ['name' => 'Darn Tough Merino Wool Hiker Socks', 'description' => 'Lifetime guaranteed merino wool socks with seamless construction, targeted cushioning, and moisture wicking.', 'price' => 28.00, 'rating' => 4.8, 'reviews_count' => 56780, 'category' => 'Clothing', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['socks', 'merino wool', 'darn tough', 'hiking', 'durable', 'comfortable', 'outdoor', 'lifetime warranty'])],
            ['name' => 'Cotopaxi Fuego Down Jacket', 'description' => '800-fill responsibly sourced down jacket with ripstop shell, zippered handwarmer pockets, and colorful Del Día option.', 'price' => 260.00, 'rating' => 4.6, 'reviews_count' => 7890, 'category' => 'Clothing', 'image_url' => null, 'is_prime' => false, 'tags' => json_encode(['jacket', 'down', 'cotopaxi', 'warm', 'winter', 'colorful', 'outdoor', 'sustainable'])],
            ['name' => 'On Cloud 5 Everyday Shoes', 'description' => 'Swiss-engineered everyday shoe with CloudTec cushioning, speed-lacing system, and recycled materials.', 'price' => 149.99, 'rating' => 4.4, 'reviews_count' => 19870, 'category' => 'Shoes', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['shoes', 'on', 'comfortable', 'lightweight', 'casual', 'walking', 'travel', 'everyday'])],

            // ─── BOOKS & LEARNING ────────────────────────────────
            ['name' => 'reMarkable 2 E-Ink Tablet', 'description' => 'Paper-like writing experience with E-Ink display, zero distraction, handwriting-to-text conversion, and cloud sync.', 'price' => 449.00, 'rating' => 4.3, 'reviews_count' => 8760, 'category' => 'Electronics', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['tablet', 'e-ink', 'remarkable', 'writing', 'notes', 'reading', 'paper', 'distraction free'])],
            ['name' => 'Rocketbook Fusion Smart Notebook', 'description' => 'Reusable notebook with 7 page styles, OCR handwriting scanning, cloud integration, and microwave-erasable pages.', 'price' => 37.00, 'rating' => 4.3, 'reviews_count' => 34560, 'category' => 'Office', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['notebook', 'reusable', 'rocketbook', 'smart', 'writing', 'notes', 'eco', 'cloud'])],
            ['name' => 'Apple Pencil Pro', 'description' => 'Advanced stylus with squeeze gesture, barrel roll, haptic feedback, Find My support, and pixel-perfect precision.', 'price' => 129.00, 'rating' => 4.7, 'reviews_count' => 15670, 'category' => 'Electronics', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['stylus', 'apple pencil', 'ipad', 'drawing', 'writing', 'digital art', 'notes', 'creative'])],
            ['name' => 'Kobo Libra Colour E-Reader', 'description' => '7-inch color E Ink Kaleido 3 display, waterproof, stylus support, Bluetooth audiobooks, and Pocket integration.', 'price' => 219.99, 'rating' => 4.5, 'reviews_count' => 6540, 'category' => 'Electronics', 'image_url' => null, 'is_prime' => false, 'tags' => json_encode(['e-reader', 'kobo', 'color', 'reading', 'books', 'waterproof', 'audiobooks', 'ebook'])],
            ['name' => 'Moleskine Classic Hardcover Notebook Large', 'description' => 'Iconic notebook with ivory-colored acid-free paper, ribbon bookmark, elastic closure, and expandable inner pocket.', 'price' => 25.95, 'rating' => 4.6, 'reviews_count' => 67890, 'category' => 'Office', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['notebook', 'moleskine', 'writing', 'journal', 'classic', 'paper', 'notes', 'premium'])],

            // ─── TRAVEL & LUGGAGE ────────────────────────────────
            ['name' => 'Away Carry-On with Pocket', 'description' => 'Hardside polycarbonate carry-on with front pocket for laptop, interior compression system, and TSA-approved lock.', 'price' => 325.00, 'rating' => 4.5, 'reviews_count' => 14560, 'category' => 'Travel', 'image_url' => null, 'is_prime' => false, 'tags' => json_encode(['luggage', 'carry-on', 'away', 'travel', 'suitcase', 'hardside', 'laptop', 'tsa'])],
            ['name' => 'Peak Design Travel Backpack 45L', 'description' => 'Expandable 30-45L travel backpack with passport pocket, shoe garage, laptop sleeve, and weatherproof 400D nylon.', 'price' => 299.95, 'rating' => 4.7, 'reviews_count' => 7890, 'category' => 'Travel', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['backpack', 'peak design', 'travel', 'expandable', 'photography', 'laptop', 'carry-on', 'adventure'])],
            ['name' => 'RIMOWA Essential Cabin Suitcase', 'description' => 'Lightweight polycarbonate carry-on with multi-wheel system, TSA-approved locks, flex divider, and 5-year warranty.', 'price' => 700.00, 'rating' => 4.4, 'reviews_count' => 5670, 'category' => 'Travel', 'image_url' => null, 'is_prime' => false, 'tags' => json_encode(['luggage', 'rimowa', 'carry-on', 'premium', 'travel', 'suitcase', 'lightweight', 'german'])],
            ['name' => 'Tortuga Outbreaker 35L Travel Backpack', 'description' => 'Maximum carry-on size backpack with lockable zippers, padded laptop/tablet sleeves, and hideaway harness system.', 'price' => 249.00, 'rating' => 4.6, 'reviews_count' => 4560, 'category' => 'Travel', 'image_url' => null, 'is_prime' => false, 'tags' => json_encode(['backpack', 'tortuga', 'travel', 'carry-on', 'one bag', 'laptop', 'digital nomad'])],
            ['name' => 'Bellroy Transit Workpack', 'description' => '20L work backpack with quick-access tech pocket, padded laptop compartment, hidden back pocket, and water-resistant fabric.', 'price' => 199.00, 'rating' => 4.5, 'reviews_count' => 8760, 'category' => 'Travel', 'image_url' => null, 'is_prime' => false, 'tags' => json_encode(['backpack', 'bellroy', 'work', 'commute', 'laptop', 'minimalist', 'professional', 'urban'])],
            ['name' => 'Aer Travel Pack 3', 'description' => '35L one-bag travel backpack with shoe pocket, water bottle pocket, clamshell opening, and 1680D Cordura nylon.', 'price' => 269.00, 'rating' => 4.6, 'reviews_count' => 6540, 'category' => 'Travel', 'image_url' => null, 'is_prime' => false, 'tags' => json_encode(['backpack', 'aer', 'travel', 'one bag', 'durable', 'cordura', 'carry-on', 'minimalist'])],

            // ─── OFFICE & PRODUCTIVITY ───────────────────────────
            ['name' => 'Herman Miller Aeron Chair', 'description' => 'Iconic ergonomic office chair with 8Z Pellicle suspension, PostureFit SL, and 3 sizes for personalized fit.', 'price' => 1395.00, 'rating' => 4.7, 'reviews_count' => 11230, 'category' => 'Office', 'image_url' => null, 'is_prime' => false, 'tags' => json_encode(['office chair', 'herman miller', 'ergonomic', 'aeron', 'comfortable', 'work', 'posture', 'premium'])],
            ['name' => 'Uplift V2 Standing Desk', 'description' => 'Electric height-adjustable desk with 4 memory presets, 355 lb capacity, anti-collision system, and bamboo top option.', 'price' => 599.00, 'rating' => 4.6, 'reviews_count' => 14560, 'category' => 'Office', 'image_url' => null, 'is_prime' => false, 'tags' => json_encode(['standing desk', 'uplift', 'adjustable', 'ergonomic', 'work', 'home office', 'electric', 'health'])],
            ['name' => 'Steelcase Leap V2 Office Chair', 'description' => 'Adaptive bolstering, LiveBack technology, natural glide system, and 4-way adjustable arms for all-day comfort.', 'price' => 1189.00, 'rating' => 4.6, 'reviews_count' => 7890, 'category' => 'Office', 'image_url' => null, 'is_prime' => false, 'tags' => json_encode(['office chair', 'steelcase', 'ergonomic', 'comfortable', 'work', 'posture', 'adjustable', 'premium'])],
            ['name' => 'BenQ ScreenBar Monitor Light', 'description' => 'USB-powered monitor light bar with auto-dimming sensor, asymmetrical optical design, and zero screen glare.', 'price' => 119.00, 'rating' => 4.6, 'reviews_count' => 19870, 'category' => 'Office', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['desk lamp', 'benq', 'monitor light', 'eye care', 'usb', 'work', 'office', 'ergonomic'])],
            ['name' => 'Autonomous SmartDesk Core', 'description' => 'Budget-friendly electric standing desk with dual motors, 4 presets, 270 lb capacity, and whisper-quiet operation.', 'price' => 449.00, 'rating' => 4.4, 'reviews_count' => 23450, 'category' => 'Office', 'image_url' => null, 'is_prime' => false, 'tags' => json_encode(['standing desk', 'autonomous', 'adjustable', 'ergonomic', 'work', 'home office', 'budget', 'electric'])],
            ['name' => 'Twelve South BookArc for MacBook', 'description' => 'Vertical stand for MacBook that saves desk space, silicone inserts for different sizes, and brushed chrome finish.', 'price' => 49.99, 'rating' => 4.5, 'reviews_count' => 11230, 'category' => 'Office', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['laptop stand', 'twelve south', 'macbook', 'desk', 'organization', 'space saving', 'office'])],
            ['name' => 'Jabra Speak 750 Speakerphone', 'description' => 'Bluetooth and USB speakerphone with full duplex audio, virtual assistant button, and link to 2nd unit for large rooms.', 'price' => 299.99, 'rating' => 4.4, 'reviews_count' => 8760, 'category' => 'Office', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['speakerphone', 'jabra', 'conference', 'meeting', 'bluetooth', 'work', 'remote', 'audio'])],

            // ─── PERSONAL CARE & GROOMING ────────────────────────
            ['name' => 'Oral-B iO Series 9 Electric Toothbrush', 'description' => 'AI-powered brushing recognition, 3D tracking, interactive color display, magnetic charging, and 7 smart modes.', 'price' => 299.99, 'rating' => 4.6, 'reviews_count' => 14560, 'category' => 'Personal Care', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['toothbrush', 'electric', 'oral-b', 'dental', 'health', 'smart', 'hygiene', 'ai'])],
            ['name' => 'Philips Norelco 9000 Prestige Shaver', 'description' => 'Wet/dry electric shaver with NanoTech precision blades, SkinIQ technology, quick-clean pod, and Qi charging pad.', 'price' => 299.96, 'rating' => 4.5, 'reviews_count' => 7890, 'category' => 'Personal Care', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['shaver', 'electric', 'philips', 'grooming', 'men', 'wet dry', 'precision', 'skin'])],
            ['name' => 'Dyson Supersonic Hair Dryer', 'description' => 'Intelligent heat control, engineered for different hair types, 5 styling attachments, and V9 digital motor.', 'price' => 429.99, 'rating' => 4.5, 'reviews_count' => 23450, 'category' => 'Personal Care', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['hair dryer', 'dyson', 'styling', 'hair care', 'fast drying', 'heat protection', 'salon'])],
            ['name' => 'Waterpik Aquarius Water Flosser', 'description' => '10 pressure settings, 7 tips, 90 seconds of water capacity, and clinically proven more effective than string floss.', 'price' => 79.99, 'rating' => 4.6, 'reviews_count' => 56780, 'category' => 'Personal Care', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['water flosser', 'waterpik', 'dental', 'flossing', 'oral health', 'hygiene', 'gums', 'teeth'])],
            ['name' => 'Philips Sonicare DiamondClean 9700', 'description' => 'Premium sonic toothbrush with 4 modes, BrushSync sensor, travel case with USB charging, and app connectivity.', 'price' => 269.99, 'rating' => 4.6, 'reviews_count' => 12340, 'category' => 'Personal Care', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['toothbrush', 'electric', 'philips', 'sonicare', 'dental', 'premium', 'hygiene', 'smart'])],

            // ─── TOYS, HOBBIES & GIFTS ───────────────────────────
            ['name' => 'Lego Star Wars Millennium Falcon UCS', 'description' => 'Ultimate Collector Series with 7,541 pieces, detailed interior, minifigures, and display stand.', 'price' => 849.99, 'rating' => 4.9, 'reviews_count' => 6540, 'category' => 'Toys', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['lego', 'star wars', 'toy', 'building', 'collector', 'display', 'gift', 'adult'])],
            ['name' => 'LEGO Botanicals Orchid', 'description' => 'Elegant display piece with buildable orchid in a faux fluted vase, adjustable blooms, and 608 pieces.', 'price' => 49.99, 'rating' => 4.8, 'reviews_count' => 18760, 'category' => 'Toys', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['lego', 'botanical', 'flower', 'decor', 'building', 'display', 'gift', 'adult', 'relaxing'])],
            ['name' => 'Cricut Maker 3', 'description' => 'Smart cutting machine for 300+ materials including fabric, leather, and balsa wood with 10X cutting force.', 'price' => 399.99, 'rating' => 4.5, 'reviews_count' => 11230, 'category' => 'Crafts', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['cricut', 'cutting machine', 'craft', 'diy', 'vinyl', 'fabric', 'creative', 'maker'])],
            ['name' => 'Fujifilm Instax Mini 12 Instant Camera', 'description' => 'Cute instant camera with automatic exposure, selfie mirror, close-up mode, and credit card-sized prints.', 'price' => 79.95, 'rating' => 4.5, 'reviews_count' => 34560, 'category' => 'Electronics', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['instant camera', 'fujifilm', 'instax', 'photo', 'retro', 'fun', 'gift', 'party', 'polaroid'])],
            ['name' => 'Ravensburger 3D Eiffel Tower Puzzle 216pc', 'description' => 'Precision-cut plastic pieces that click together without glue to build a 18-inch Eiffel Tower with LED lighting option.', 'price' => 36.99, 'rating' => 4.7, 'reviews_count' => 9870, 'category' => 'Toys', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['puzzle', '3d', 'ravensburger', 'building', 'eiffel tower', 'decoration', 'gift', 'hobby'])],
            ['name' => 'Theragun Mini 2.0', 'description' => 'Ultra-portable percussive therapy device weighing just 1.3 lbs with 3 speeds and QuietForce Technology.', 'price' => 199.00, 'rating' => 4.4, 'reviews_count' => 12340, 'category' => 'Health', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['massage gun', 'theragun', 'portable', 'recovery', 'muscle', 'travel', 'compact', 'therapy'])],
            ['name' => 'Nintendo Switch Pro Controller', 'description' => 'Premium wireless controller with motion controls, HD rumble, NFC for amiibo, and 40-hour battery.', 'price' => 69.99, 'rating' => 4.7, 'reviews_count' => 45670, 'category' => 'Gaming', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['controller', 'nintendo', 'switch', 'gaming', 'wireless', 'pro', 'comfortable'])],
            ['name' => 'Polaroid Go Gen 2 Instant Camera', 'description' => 'Smallest analog instant camera with selfie mirror, dynamic flash, double exposure, and self-timer.', 'price' => 79.99, 'rating' => 4.3, 'reviews_count' => 7890, 'category' => 'Electronics', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['instant camera', 'polaroid', 'retro', 'photo', 'mini', 'fun', 'gift', 'analog'])],
            ['name' => 'Tile Mate Bluetooth Tracker 4-Pack', 'description' => 'Compact item trackers with 250 ft range, replaceable battery, water-resistant, and community find network.', 'price' => 54.99, 'rating' => 4.3, 'reviews_count' => 34560, 'category' => 'Electronics', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['tracker', 'tile', 'bluetooth', 'find', 'keys', 'wallet', 'lost', 'locator'])],
            ['name' => 'Apple AirTag 4-Pack', 'description' => 'Precision finding with Ultra Wideband, built-in speaker, replaceable battery, IP67 water resistant, and Find My network.', 'price' => 99.00, 'rating' => 4.7, 'reviews_count' => 45670, 'category' => 'Electronics', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['tracker', 'apple', 'airtag', 'find my', 'keys', 'wallet', 'luggage', 'locator'])],

            // ─── BABY & KIDS ─────────────────────────────────────
            ['name' => 'UPPAbaby VISTA V2 Stroller', 'description' => 'Full-size expandable stroller accommodating up to 3 children, all-wheel suspension, one-step fold, and bassinet included.', 'price' => 1099.99, 'rating' => 4.7, 'reviews_count' => 8760, 'category' => 'Baby', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['stroller', 'uppababy', 'baby', 'kids', 'travel', 'expandable', 'premium', 'family'])],
            ['name' => 'Hatch Rest+ Sound Machine', 'description' => 'Smart sound machine and night light with clock, OK-to-wake alert, app control, and sleep programs for kids.', 'price' => 89.99, 'rating' => 4.6, 'reviews_count' => 23450, 'category' => 'Baby', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['sound machine', 'hatch', 'baby', 'sleep', 'night light', 'kids', 'white noise', 'toddler'])],
            ['name' => 'Nugget Comfort Play Couch', 'description' => 'Versatile foam play couch with 4 configurable pieces, machine-washable microsuede covers, and endless build possibilities.', 'price' => 259.00, 'rating' => 4.8, 'reviews_count' => 15670, 'category' => 'Baby', 'image_url' => null, 'is_prime' => false, 'tags' => json_encode(['play couch', 'nugget', 'kids', 'creative', 'furniture', 'toddler', 'imaginative play', 'foam'])],
            ['name' => 'Lovevery Play Kits Subscription', 'description' => 'Stage-based play kits with Montessori-aligned toys, play guides, and developmental milestones for ages 0-4.', 'price' => 80.00, 'rating' => 4.5, 'reviews_count' => 11230, 'category' => 'Baby', 'image_url' => null, 'is_prime' => false, 'tags' => json_encode(['toys', 'lovevery', 'baby', 'montessori', 'educational', 'development', 'subscription', 'play'])],
            ['name' => 'Owlet Dream Sock Baby Monitor', 'description' => 'Smart sock that tracks heart rate and oxygen levels, notifications to phone, and sleep quality analytics.', 'price' => 299.00, 'rating' => 4.3, 'reviews_count' => 14560, 'category' => 'Baby', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['baby monitor', 'owlet', 'health', 'sleep', 'heart rate', 'oxygen', 'smart', 'safety'])],

            // ─── PET SUPPLIES ────────────────────────────────────
            ['name' => 'Litter-Robot 4 Self-Cleaning Litter Box', 'description' => 'Automatic sifting with OmniSense weight sensor, quiet operation, app tracking, and carbon-filtered drawer.', 'price' => 699.00, 'rating' => 4.4, 'reviews_count' => 9870, 'category' => 'Pets', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['cat', 'litter box', 'automatic', 'self cleaning', 'smart', 'pet', 'litter robot'])],
            ['name' => 'Furbo 360° Dog Camera', 'description' => 'Full-room 360° rotating camera with treat tossing, barking alerts, 1080p video, 2-way audio, and night vision.', 'price' => 210.00, 'rating' => 4.4, 'reviews_count' => 18760, 'category' => 'Pets', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['dog camera', 'furbo', 'pet', 'treat', 'monitor', 'smart home', 'dog', 'remote'])],
            ['name' => 'Fi Series 3 Smart Dog Collar', 'description' => 'GPS dog tracker with LTE, escape alerts, step tracking, sleep monitoring, and 3-month battery life.', 'price' => 149.00, 'rating' => 4.3, 'reviews_count' => 7890, 'category' => 'Pets', 'image_url' => null, 'is_prime' => false, 'tags' => json_encode(['dog collar', 'gps', 'fi', 'tracker', 'pet', 'smart', 'dog', 'safety', 'lte'])],
            ['name' => 'PetSafe ScoopFree Crystal Litter Box', 'description' => 'Self-cleaning litter box with disposable crystal trays, health counter, leak protection, and weeks of no scooping.', 'price' => 189.95, 'rating' => 4.2, 'reviews_count' => 23450, 'category' => 'Pets', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['cat', 'litter box', 'self cleaning', 'petsafe', 'crystal', 'pet', 'low maintenance'])],
            ['name' => 'Wisdom Panel Premium Dog DNA Test', 'description' => 'Tests for 350+ breeds, 235+ health conditions, 45+ trait tests, and connects with veterinarians for results.', 'price' => 159.99, 'rating' => 4.4, 'reviews_count' => 11230, 'category' => 'Pets', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['dog', 'dna test', 'pet', 'health', 'breed', 'wisdom panel', 'genetic', 'veterinary'])],

            // ─── CAR & AUTO ──────────────────────────────────────
            ['name' => 'Viofo A129 Plus Duo Dash Cam', 'description' => 'Dual-channel dash cam with 2K front, 1080p rear, GPS, Wi-Fi, parking mode, and 140° wide angle.', 'price' => 169.99, 'rating' => 4.5, 'reviews_count' => 14560, 'category' => 'Auto', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['dash cam', 'viofo', 'car', 'camera', 'safety', 'driving', 'gps', 'dual'])],
            ['name' => 'NOCO Boost Plus GB40 Jump Starter', 'description' => '1000A 12V lithium jump starter for up to 6L gas engines, USB power bank, LED flashlight, and spark-proof design.', 'price' => 99.95, 'rating' => 4.7, 'reviews_count' => 67890, 'category' => 'Auto', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['jump starter', 'noco', 'car', 'battery', 'emergency', 'portable', 'power bank', 'roadside'])],
            ['name' => 'Thule Motion XT Rooftop Cargo Box', 'description' => 'Aerodynamic cargo box with dual-side opening, PowerClick quick-mount, SlideLock system, and 16 cubic ft capacity.', 'price' => 749.95, 'rating' => 4.6, 'reviews_count' => 5670, 'category' => 'Auto', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['cargo box', 'thule', 'rooftop', 'car', 'storage', 'travel', 'road trip', 'skiing'])],
            ['name' => 'Michelin CrossClimate 2 All-Season Tires', 'description' => 'All-season tire with V-shaped tread for wet grip, Thermal Adaptive compound, and 60,000-mile warranty.', 'price' => 189.99, 'rating' => 4.7, 'reviews_count' => 23450, 'category' => 'Auto', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['tires', 'michelin', 'car', 'all season', 'driving', 'safety', 'wet', 'snow'])],
            ['name' => 'Chemical Guys Car Wash Kit 16-Piece', 'description' => 'Complete detailing kit with foam cannon, microfiber towels, tire gel, interior cleaner, and bucket with grit guard.', 'price' => 89.99, 'rating' => 4.5, 'reviews_count' => 18760, 'category' => 'Auto', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['car wash', 'detailing', 'chemical guys', 'cleaning', 'car care', 'wax', 'polish', 'microfiber'])],

            // ─── MUSIC & INSTRUMENTS ─────────────────────────────
            ['name' => 'Fender Player Stratocaster Electric Guitar', 'description' => 'Classic Strat with alder body, maple neck, 3 Player Series pickups, 2-point tremolo, and vintage-style tuners.', 'price' => 849.99, 'rating' => 4.7, 'reviews_count' => 8760, 'category' => 'Musical Instruments', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['guitar', 'electric', 'fender', 'stratocaster', 'music', 'instrument', 'rock', 'blues'])],
            ['name' => 'Yamaha P-225 Digital Piano', 'description' => '88-key weighted action digital piano with GHS keys, 24 voices, Bluetooth MIDI, and built-in speakers.', 'price' => 749.99, 'rating' => 4.6, 'reviews_count' => 6540, 'category' => 'Musical Instruments', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['piano', 'digital', 'yamaha', 'keyboard', 'music', 'instrument', 'weighted keys', 'beginner'])],
            ['name' => 'Audio-Technica AT2020 Condenser Microphone', 'description' => 'Cardioid condenser microphone with low mass diaphragm, wide frequency response, and high SPL handling.', 'price' => 99.00, 'rating' => 4.6, 'reviews_count' => 34560, 'category' => 'Musical Instruments', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['microphone', 'condenser', 'audio-technica', 'recording', 'podcast', 'streaming', 'studio', 'vocal'])],
            ['name' => 'Roland TD-17KVX Electronic Drum Kit', 'description' => 'V-Drums with mesh heads, Prismatic Sound Modeling, Bluetooth audio, coaching functions, and 50 preset kits.', 'price' => 1999.99, 'rating' => 4.7, 'reviews_count' => 4560, 'category' => 'Musical Instruments', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['drums', 'electronic', 'roland', 'v-drums', 'music', 'instrument', 'practice', 'quiet'])],
            ['name' => 'Shure SM7B Dynamic Microphone', 'description' => 'Industry-standard vocal microphone with flat frequency response, air suspension shock isolation, and electromagnetic shielding.', 'price' => 399.00, 'rating' => 4.8, 'reviews_count' => 19870, 'category' => 'Musical Instruments', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['microphone', 'dynamic', 'shure', 'podcast', 'recording', 'streaming', 'studio', 'vocal', 'professional'])],
            ['name' => 'Focusrite Scarlett 2i2 4th Gen Audio Interface', 'description' => 'USB-C audio interface with 2 mic preamps, Air mode, auto-gain, clip-safe feature, and studio-quality converters.', 'price' => 179.99, 'rating' => 4.7, 'reviews_count' => 23450, 'category' => 'Musical Instruments', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['audio interface', 'focusrite', 'scarlett', 'recording', 'usb', 'studio', 'music production', 'podcast'])],

            // ─── GARDEN & OUTDOOR LIVING ─────────────────────────
            ['name' => 'Ego Power+ 56V Lawn Mower', 'description' => 'Cordless 21-inch self-propelled mower with 56V ARC Lithium battery, 45-min runtime, and 7-position cutting height.', 'price' => 549.00, 'rating' => 4.6, 'reviews_count' => 14560, 'category' => 'Garden', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['lawn mower', 'ego', 'cordless', 'battery', 'garden', 'yard', 'electric', 'lawn care'])],
            ['name' => 'AeroGarden Bounty Indoor Garden', 'description' => 'Countertop hydroponic garden growing up to 9 pods, 24-inch grow height, LED grow lights, and touchscreen controls.', 'price' => 189.95, 'rating' => 4.4, 'reviews_count' => 18760, 'category' => 'Garden', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['indoor garden', 'aerogarden', 'hydroponic', 'herbs', 'growing', 'kitchen', 'plants', 'smart'])],
            ['name' => 'Weber Spirit II E-310 Gas Grill', 'description' => '3-burner gas grill with 529 sq in cooking area, GS4 grilling system, iGrill 3 compatible, and open cart design.', 'price' => 519.00, 'rating' => 4.6, 'reviews_count' => 23450, 'category' => 'Garden', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['grill', 'weber', 'gas', 'bbq', 'outdoor cooking', 'patio', 'burgers', 'backyard'])],
            ['name' => 'Rain Bird Smart WiFi Sprinkler Timer', 'description' => '8-zone smart irrigation controller with weather-based watering, EPA WaterSense certified, and seasonal adjust.', 'price' => 129.89, 'rating' => 4.4, 'reviews_count' => 9870, 'category' => 'Garden', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['sprinkler', 'smart', 'rain bird', 'irrigation', 'garden', 'lawn', 'water saving', 'wifi'])],
            ['name' => 'Solo Stove Bonfire 2.0 Fire Pit', 'description' => 'Smokeless stainless steel fire pit with signature 360° airflow, removable ash pan, and 19.5-inch diameter.', 'price' => 299.99, 'rating' => 4.6, 'reviews_count' => 15670, 'category' => 'Garden', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['fire pit', 'solo stove', 'smokeless', 'outdoor', 'patio', 'camping', 'stainless steel', 'backyard'])],

            // ─── SUPPLEMENTS & WELLNESS ──────────────────────────
            ['name' => 'Athletic Greens AG1 Supplement', 'description' => 'Comprehensive daily nutrition drink with 75 vitamins, minerals, probiotics, adaptogens, and whole food sourced ingredients.', 'price' => 99.00, 'rating' => 4.3, 'reviews_count' => 23450, 'category' => 'Health', 'image_url' => null, 'is_prime' => false, 'tags' => json_encode(['supplement', 'greens', 'vitamins', 'health', 'nutrition', 'probiotics', 'wellness', 'daily'])],
            ['name' => 'Calm Magnesium Gummies', 'description' => 'Magnesium citrate gummies supporting relaxation, sleep quality, and muscle recovery with natural raspberry flavor.', 'price' => 21.99, 'rating' => 4.5, 'reviews_count' => 45670, 'category' => 'Health', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['magnesium', 'supplement', 'sleep', 'relaxation', 'calm', 'gummies', 'wellness', 'recovery'])],
            ['name' => 'Beam Dream Powder Sleep Supplement', 'description' => 'Hot cocoa sleep blend with nano hemp, reishi, magnesium, l-theanine, and melatonin for better sleep quality.', 'price' => 46.00, 'rating' => 4.2, 'reviews_count' => 8760, 'category' => 'Health', 'image_url' => null, 'is_prime' => false, 'tags' => json_encode(['sleep', 'supplement', 'beam', 'melatonin', 'cocoa', 'relaxation', 'wellness', 'night'])],
            ['name' => 'Seed DS-01 Daily Synbiotic Probiotic', 'description' => 'Clinically studied probiotic + prebiotic with 24 strains, 53.6 billion AFU, and patented capsule-in-capsule delivery.', 'price' => 49.99, 'rating' => 4.3, 'reviews_count' => 11230, 'category' => 'Health', 'image_url' => null, 'is_prime' => false, 'tags' => json_encode(['probiotic', 'seed', 'gut health', 'digestive', 'wellness', 'supplement', 'prebiotic', 'microbiome'])],
            ['name' => 'Liquid I.V. Hydration Multiplier 16-Pack', 'description' => 'Electrolyte drink mix using Cellular Transport Technology for 2x faster hydration than water alone.', 'price' => 23.96, 'rating' => 4.6, 'reviews_count' => 78900, 'category' => 'Health', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['hydration', 'electrolyte', 'liquid iv', 'drink', 'recovery', 'sports', 'wellness', 'travel'])],

            // ─── PHOTOGRAPHY ACCESSORIES ─────────────────────────
            ['name' => 'Peak Design Everyday Backpack V2 20L', 'description' => 'Camera backpack with FlexFold dividers, MagLatch closure, weatherproof 400D nylon, and external carry straps.', 'price' => 279.95, 'rating' => 4.7, 'reviews_count' => 9870, 'category' => 'Electronics', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['camera bag', 'peak design', 'backpack', 'photography', 'laptop', 'travel', 'everyday', 'weatherproof'])],
            ['name' => 'Manfrotto Befree Advanced Tripod', 'description' => 'Travel tripod with ball head, 8.8 lb capacity, twist locks, folding to 15.75 inches, and quick-release plate.', 'price' => 219.99, 'rating' => 4.5, 'reviews_count' => 7890, 'category' => 'Electronics', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['tripod', 'manfrotto', 'photography', 'camera', 'travel', 'compact', 'stable', 'video'])],
            ['name' => 'SanDisk Extreme PRO 256GB SD Card', 'description' => 'UHS-I SD card with 200MB/s read, 140MB/s write, 4K UHD video capable, and built-in write-protect switch.', 'price' => 37.99, 'rating' => 4.8, 'reviews_count' => 56780, 'category' => 'Electronics', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['sd card', 'sandisk', 'memory', 'storage', 'camera', 'photography', 'fast', '4k'])],
            ['name' => 'DJI Osmo Mobile 6 Smartphone Gimbal', 'description' => '3-axis smartphone gimbal with ActiveTrack 6.0, gesture control, story mode, and foldable design.', 'price' => 139.00, 'rating' => 4.5, 'reviews_count' => 11230, 'category' => 'Electronics', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['gimbal', 'dji', 'smartphone', 'stabilizer', 'video', 'content creation', 'vlogging', 'smooth'])],
            ['name' => 'Godox SL-60W LED Video Light', 'description' => 'Continuous LED light with 60W output, Bowens mount, remote control, 5600K daylight, and quiet fan cooling.', 'price' => 129.00, 'rating' => 4.5, 'reviews_count' => 14560, 'category' => 'Electronics', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['video light', 'godox', 'led', 'photography', 'studio', 'lighting', 'youtube', 'continuous'])],

            // ─── POWER & ENERGY ──────────────────────────────────
            ['name' => 'EcoFlow DELTA 2 Portable Power Station', 'description' => '1024Wh LFP battery with 1800W output, 80% charge in 50 min, 15 outlets, and 3000+ cycle lifespan.', 'price' => 999.00, 'rating' => 4.6, 'reviews_count' => 7890, 'category' => 'Electronics', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['power station', 'ecoflow', 'portable', 'battery', 'camping', 'emergency', 'solar', 'off grid'])],
            ['name' => 'Jackery Explorer 300 Plus', 'description' => 'Compact 288Wh portable power station with 300W output, LFP battery, 3000+ cycles, and solar panel compatible.', 'price' => 249.00, 'rating' => 4.5, 'reviews_count' => 14560, 'category' => 'Electronics', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['power station', 'jackery', 'portable', 'battery', 'camping', 'solar', 'compact', 'travel'])],
            ['name' => 'Goal Zero Nomad 50 Solar Panel', 'description' => 'Foldable 50W monocrystalline solar panel with kickstand, USB output, chainable design, and weather-resistant.', 'price' => 249.95, 'rating' => 4.4, 'reviews_count' => 6540, 'category' => 'Electronics', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['solar panel', 'goal zero', 'portable', 'charging', 'camping', 'renewable', 'off grid', 'outdoor'])],
            ['name' => 'Anker Prime 20,000mAh Power Bank', 'description' => '200W portable charger with smart digital display, ActiveShield 2.0, and charges MacBook Pro to 50% in 30 min.', 'price' => 129.99, 'rating' => 4.6, 'reviews_count' => 11230, 'category' => 'Electronics', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['power bank', 'anker', 'portable charger', 'battery', 'fast charging', 'usb-c', 'laptop', 'travel'])],
            ['name' => 'Belkin BoostCharge Pro 3-in-1 MagSafe Charger', 'description' => 'Charges iPhone, Apple Watch, and AirPods simultaneously with official MagSafe, 15W, and StandBy mode support.', 'price' => 149.99, 'rating' => 4.5, 'reviews_count' => 18760, 'category' => 'Electronics', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['charger', 'wireless', 'belkin', 'magsafe', 'iphone', 'apple watch', 'airpods', '3-in-1'])],

            // ─── BOARD GAMES & PUZZLES ───────────────────────────
            ['name' => 'Wingspan Board Game', 'description' => 'Engine-building card game about bird enthusiasts with 170 unique bird cards, custom dice, and stunning artwork.', 'price' => 45.00, 'rating' => 4.8, 'reviews_count' => 23450, 'category' => 'Toys', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['board game', 'wingspan', 'strategy', 'card game', 'birds', 'family', 'hobby', 'tabletop'])],
            ['name' => 'Catan Board Game', 'description' => 'Classic resource-trading strategy game for 3-4 players with modular hex board, development cards, and trade mechanics.', 'price' => 35.49, 'rating' => 4.7, 'reviews_count' => 67890, 'category' => 'Toys', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['board game', 'catan', 'strategy', 'trading', 'family', 'classic', 'multiplayer', 'tabletop'])],
            ['name' => 'Codenames Party Game', 'description' => 'Word association game for 2-8+ players where spymasters give one-word clues to identify secret agents.', 'price' => 15.99, 'rating' => 4.7, 'reviews_count' => 45670, 'category' => 'Toys', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['board game', 'codenames', 'party', 'word game', 'group', 'fun', 'social', 'family'])],
            ['name' => 'Azul Board Game', 'description' => 'Tile-drafting game inspired by Portuguese azulejo tiles with beautiful components, simple rules, and deep strategy.', 'price' => 27.99, 'rating' => 4.7, 'reviews_count' => 19870, 'category' => 'Toys', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['board game', 'azul', 'strategy', 'tile', 'beautiful', 'abstract', 'family', 'tabletop'])],
            ['name' => 'Ticket to Ride Board Game', 'description' => 'Cross-country train adventure for 2-5 players collecting cards to claim railway routes across North America.', 'price' => 39.29, 'rating' => 4.8, 'reviews_count' => 34560, 'category' => 'Toys', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['board game', 'ticket to ride', 'trains', 'family', 'strategy', 'classic', 'multiplayer', 'geography'])],

            // ─── STORAGE & ORGANIZATION ──────────────────────────
            ['name' => 'Synology DS224+ NAS', 'description' => '2-bay NAS with Intel Celeron J4125, 2GB DDR4, dual 1GbE, hardware transcoding, and DiskStation Manager OS.', 'price' => 299.99, 'rating' => 4.7, 'reviews_count' => 8760, 'category' => 'Computers', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['nas', 'synology', 'storage', 'backup', 'server', 'network', 'media', 'home'])],
            ['name' => 'Western Digital Red Plus 8TB NAS HDD', 'description' => 'CMR NAS drive with 256MB cache, 5640 RPM, 180 TB/year workload, and NASware 3.0 firmware.', 'price' => 159.99, 'rating' => 4.6, 'reviews_count' => 23450, 'category' => 'Computers', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['hard drive', 'hdd', 'wd', 'nas', 'storage', 'backup', '8tb', 'reliable'])],
            ['name' => 'Samsung T7 Shield 2TB Portable SSD', 'description' => 'Rugged portable SSD with 1,050 MB/s transfer, IP65 dust/water resistance, rubber exterior, and USB 3.2 Gen 2.', 'price' => 159.99, 'rating' => 4.7, 'reviews_count' => 18760, 'category' => 'Computers', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['ssd', 'portable', 'samsung', 'storage', 'rugged', 'fast', 'usb', 'backup', 'travel'])],

            // ─── MISCELLANEOUS / UNIQUE ──────────────────────────
            ['name' => 'Oura Ring Gen 3 Horizon', 'description' => 'Sleek circular smart ring tracking sleep, readiness, activity, blood oxygen, and temperature trends with titanium design.', 'price' => 349.00, 'rating' => 4.4, 'reviews_count' => 7890, 'category' => 'Wearables', 'image_url' => null, 'is_prime' => false, 'tags' => json_encode(['smart ring', 'oura', 'sleep', 'fitness', 'health', 'tracker', 'wearable', 'titanium'])],
            ['name' => 'Bala Bangles 2 lb Wrist Weights', 'description' => 'Stylish wearable wrist and ankle weights with recycled stainless steel bars, silicone clasp, and 2 lb each.', 'price' => 65.00, 'rating' => 4.4, 'reviews_count' => 14560, 'category' => 'Fitness', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['weights', 'wrist', 'bala', 'fitness', 'walking', 'workout', 'stylish', 'strength'])],
            ['name' => 'Ember Mug 2 Temperature Control', 'description' => 'Smart heated coffee mug maintaining your chosen temperature from 120°F-145°F, 80-min battery, and app control.', 'price' => 149.95, 'rating' => 4.3, 'reviews_count' => 19870, 'category' => 'Kitchen', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['mug', 'heated', 'ember', 'coffee', 'tea', 'smart', 'temperature', 'gift', 'office'])],
            ['name' => 'Lexon Mino+ Portable Bluetooth Speaker', 'description' => 'Palm-sized floating speaker with 3W output, TWS pairing, selfie remote, wireless charging pad, and IPX7 waterproof.', 'price' => 39.90, 'rating' => 4.3, 'reviews_count' => 6540, 'category' => 'Electronics', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['speaker', 'bluetooth', 'portable', 'mini', 'waterproof', 'lexon', 'floating', 'gift', 'cute'])],
            ['name' => 'Bellroy Slim Sleeve Wallet', 'description' => 'Minimalist leather wallet for 4-12 cards with pull-tab access, premium vegetable-tanned leather, and RFID protection.', 'price' => 89.00, 'rating' => 4.6, 'reviews_count' => 11230, 'category' => 'Accessories', 'image_url' => null, 'is_prime' => false, 'tags' => json_encode(['wallet', 'bellroy', 'leather', 'slim', 'minimalist', 'rfid', 'men', 'gift', 'edc'])],
            ['name' => 'Ridge Wallet Titanium', 'description' => 'RFID-blocking titanium wallet holding 1-12 cards with money clip or cash strap, lifetime warranty.', 'price' => 125.00, 'rating' => 4.5, 'reviews_count' => 23450, 'category' => 'Accessories', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['wallet', 'ridge', 'titanium', 'minimalist', 'rfid', 'metal', 'edc', 'gift', 'slim'])],
            ['name' => 'Yoto Player Kids Audio Player', 'description' => 'Screen-free audio player for kids with physical story/music cards, night light, Bluetooth, and parental controls.', 'price' => 99.99, 'rating' => 4.7, 'reviews_count' => 18760, 'category' => 'Baby', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['kids', 'audio', 'yoto', 'stories', 'music', 'screen free', 'educational', 'toddler', 'gift'])],
            ['name' => 'Timemore Chestnut C3 Hand Grinder', 'description' => 'Portable manual coffee grinder with stainless steel conical burrs, CNC aluminum body, and adjustable click settings.', 'price' => 64.90, 'rating' => 4.6, 'reviews_count' => 9870, 'category' => 'Kitchen', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['coffee grinder', 'manual', 'timemore', 'pour over', 'espresso', 'portable', 'travel', 'brewing'])],
            ['name' => 'Analogue Pocket Handheld Console', 'description' => 'Premium retro gaming handheld with 3.5-inch LTPS LCD, FPGA-based emulation, plays original Game Boy cartridges.', 'price' => 249.99, 'rating' => 4.6, 'reviews_count' => 5670, 'category' => 'Gaming', 'image_url' => null, 'is_prime' => false, 'tags' => json_encode(['retro gaming', 'analogue', 'handheld', 'game boy', 'portable', 'fpga', 'classic', 'nostalgia'])],
            ['name' => 'Meross Smart Power Strip', 'description' => 'Wi-Fi surge protector with 4 smart outlets, 4 USB ports, voice control, scheduling, and energy monitoring.', 'price' => 29.99, 'rating' => 4.4, 'reviews_count' => 34560, 'category' => 'Smart Home', 'image_url' => null, 'is_prime' => true, 'tags' => json_encode(['power strip', 'smart', 'meross', 'wifi', 'alexa', 'surge protector', 'usb', 'energy'])],
        ];

        // Generate image URLs for products without them
        foreach ($products as &$product) {
            if ($product['image_url'] === null) {
                $slug = strtolower($product['name']);
                $slug = str_replace(["'", '"', '&', '+', '°', '%'], ['', '', 'and', 'plus', '', 'percent'], $slug);
                $slug = preg_replace('/[^a-z0-9]+/', '-', $slug);
                $slug = trim($slug, '-');
                $product['image_url'] = "https://picsum.photos/seed/{$slug}/400/400";
            }
        }
        unset($product);

        // Skip products that already exist in the database
        $existingNames = DB::table('products')->pluck('name')->all();
        $products = array_values(array_filter($products, fn ($p) => ! in_array($p['name'], $existingNames)));

        if (empty($products)) {
            $this->command->info('All products already exist. Skipping seeding.');

            return;
        }

        $now = now();

        foreach ($products as &$product) {
            $product['created_at'] = $now;
            $product['updated_at'] = $now;
        }
        unset($product);

        // Insert in chunks to avoid memory issues
        foreach (array_chunk($products, 50) as $chunk) {
            DB::table('products')->insert($chunk);
        }

        $this->command->info('Seeded ' . count($products) . ' products.');
        $this->command->info('Run `php artisan products:embed` to generate embeddings.');
    }
}